# export go path
export GOPATH=/workspace/golang
# add go path
PATH=$PATH:$GOPATH/bin
# add brew path
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

export PATH=$PATH
export PATH="/usr/local/opt/gettext/bin:$PATH"
export PATH="/usr/local/opt/node@6/bin:$PATH"
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

export PATH="/opt/xtensa-esp32-elf/bin:/usr/local/opt/mysql-client/bin:$PATH"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/morpheus/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/morpheus/google-cloud-sdk/path.zsh.inc'; fi
export IDF_PATH="/workspace/6c/iot/esp-idf"
export PATH="/Library/TeX/texbin:$PATH"
export RIME_PATH="~/.oh-my-env/06-emacs.d/librime"
