
# desktop applications 
cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/versions'
cask 'appcleaner'
cask 'google-chrome'
cask 'intellij-idea'
cask 'neteasemusic'
cask 'alfred'
cask 'mou'
cask 'sequel-pro'
cask 'iterm2'
cask 'sublime-text3'


# terminal apps
brew 'tig'
brew 'ag'
brew 'jq'
brew 'git'
brew 'vim'

