# desktop applications 
cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/versions'

# system
cask 'docker'
cask 'java8'
cask 'iterm2'
cask 'sogouinput'
cask 'shadowsocksx-ng'
cask 'snipaste'
# usb network sharing driver
cask 'horndis'
brew 'ruby'

# productivity
cask 'alfred'
cask 'xmind'
cask 'near-lock'
cask 'hammerspoon'
cask 'appcleaner'
cask 'cheatsheet'
cask 'cleanmymac'
brew 'mu'
brew 'offlineimap', restart_service: :changde

# editor
cask 'sublime-text'
cask 'macdown'
brew 'emacs'
cask 'arduino'

# storage
cask 'baidunetdisk'
cask 'baiducloud'
cask 'evernote'
cask 'dash'
cask 'thunder'
cask '1password'

# broswer
cask 'firefox'
cask 'google-chrome'

# study
cask 'kindle'
cask 'youdaodict'

# entertain
cask 'neteasemusic'
cask 'qqmusic'
cask 'vlc'

# communication
cask 'qq'

# emacs
cask "mactex-no-gui"
# terminal apps
## network
brew 'telnet'
brew 'nmap'
brew 'axel' # multiple thread downloader
brew 'iperf'
brew 'gradle'
brew 'cmake'
brew 'tig'
brew 'rg'
brew 'jq'
brew 'autojump'
brew 'git'
brew 'vim'
brew 'zsh'
brew 'tldr'
brew 'zsh-completions'
brew 'graphviz'
brew 'tree'

brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'tmuxinator-completion'
brew 'mycli'
# code statictis
brew 'cloc'
brew 'golang'
brew 'maven'
brew 'fzf'
brew 'watch'

brew 'zplug'

# other
cask 'logitech-options'
