
# desktop applications 
cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/versions'
cask 'appcleaner'
cask 'google-chrome'
cask 'neteasemusic'
cask 'alfred'
cask 'mou'
cask 'iterm2'
cask 'sublime-text3'
cask 'vagrant'


# terminal apps
brew 'tig'
brew 'ag'
brew 'jq'
brew 'autojump'
brew 'git'
brew 'vim'
brew 'zsh'
brew 'zsh-completions'
brew 'tmux'
brew 'homebrew/completions/tmuxinator-completion'
brew 'cmake'

# for dev ops
brew 'ansible'
brew 'dnsmasq'
